export enum AuthActionTypes {
  SIGN_IN_REQUEST = "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE = "SIGN_IN_FAILURE",

  SIGN_UP_REQUEST = "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE = "SIGN_UP_FAILURE",

  SIGN_OUT = "SIGN_OUT",
  CLEAR_ERRORS = "CLEAR_ERRORS"
}
