export enum OfferActionTypes {
  ADD_OFFER_REQUEST = "ADD_OFFER_REQUEST",
  ADD_OFFER_SUCCESS = "ADD_OFFER_SUCCESS",
  ADD_OFFER_FAILURE = "ADD_OFFER_FAILURE",

  GET_OFFER_REQUEST = "GET_OFFER_REQUEST",
  GET_OFFER_SUCCESS = "GET_OFFER_SUCCESS",
  GET_OFFER_FAILURE = "GET_OFFER_FAILURE",

  DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST",
  DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS",
  DELETE_OFFER_FAILURE = "DELETE_OFFER_FAILURE"
}
