export enum ReservationActionTypes {
  ADD_RESERVATION_REQUEST = "ADD_RESERVATION_REQUEST",
  ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS",
  ADD_RESERVATION_FAILURE = "ADD_RESERVATION_FAILURE",

  GET_RESERVATIONS_REQUEST = "GET_RESERVATIONS_REQUEST",
  GET_RESERVATIONS_SUCCESS = "GET_RESERVATIONS_SUCCESS",
  GET_RESERVATIONS_FAILURE = "GET_RESERVATIONS_FAILURE"
}
