export enum ReservationActionTypes {
  ADD_RESERVATION_REQUEST = "ADD_RESERVATION_REQUEST",
  ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS",
  ADD_RESERVATION_FAILURE = "ADD_RESERVATION_FAILURE",

  GET_TRAINER_RESERVATIONS_REQUEST = "GET_TRAINER_RESERVATIONS_REQUEST",
  GET_TRAINER_RESERVATIONS_SUCCESS = "GET_TRAINER_RESERVATIONS_SUCCESS",
  GET_TRAINER_RESERVATIONS_FAILURE = "GET_TRAINER_RESERVATIONS_FAILURE",

  GET_USER_RESERVATIONS_REQUEST = "GET_USER_RESERVATIONS_REQUEST",
  GET_USER_RESERVATIONS_SUCCESS = "GET_USER_RESERVATIONS_SUCCESS",
  GET_USER_RESERVATIONS_FAILURE = "GET_USER_RESERVATIONS_FAILURE"
}
