export enum CommentActionTypes {
  ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE",

  GET_TRAINER_COMMENTS_REQUEST = 'GET_TRAINER_COMMENTS_REQUEST',  
  GET_TRAINER_COMMENTS_SUCCESS = 'GET_TRAINER_COMMENTS_SUCCESS',  
  GET_TRAINER_COMMENTS_FAILURE = 'GET_TRAINER_COMMENTS_FAILURE',  
}
